#!/bin/bash

# braucht sox. Skript-Argument is die 30-Kanaelige .wav Datei
# NB Kanal 4 bleibt leer, ausser man hat etwas auf den Sub explizit getan

# wenn Skript im .wav Verzeichniss ist dann: cd "$(dirname "$0")"

if ! [ -x "$(command -v sox)" ]; then
    echo "This script needs sox. "
    echo "Try 'brew install sox' on MacOS or 'apt-get install sox' on Linux"
    exit
fi

if [ $# -eq 0 ]
  then
      echo "This script needs 1 argument: the path to the 30-channel .wav file"
      exit
fi

# neuer Name basiert auf Argument 1
out="${1%.wav}-channels-25-30.wav"
echo "*** Give the original file and the file with channels 25-30 to Beschallung"
echo "Writing channels 25-30 to "
echo "$out"
echo "NB the input file remains unchanged"

sox "$1" "$out" remix 25 26 27 28 29 30
